# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc
alias st='git status'
alias push='git push'
alias com='git commit -am'
alias pull='git pull'
alias chm='git checkout master'
alias ch='git checkout'
alias p='git push; git commit -am'

